# Generated by Django 4.1.5 on 2023-01-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='source',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
