# Generated by Django 4.1.5 on 2023-01-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recapp', '0006_alter_crawlingtarget_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardarticle',
            unique_together={('dashboard', 'article')},
        ),
    ]
