# Generated by Django 4.1.5 on 2023-02-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recapp", "0007_alter_dashboard_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="notifications",
            field=models.CharField(
                choices=[
                    ("weekly", "weekly"),
                    ("daily", "daily"),
                    ("monthly", "monthly"),
                ],
                default="disabled",
                max_length=100,
            ),
        ),
    ]
