# Generated by Django 4.1.5 on 2023-02-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recapp", "0008_dashboard_notifications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crawlingtarget",
            name="last_crawl",
        ),
        migrations.RemoveField(
            model_name="crawlingtarget",
            name="last_successful_crawl",
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="notifications",
            field=models.CharField(
                choices=[
                    ("weekly", "weekly"),
                    ("daily", "daily"),
                    ("monthly", "monthly"),
                    ("disabled", "disabled"),
                ],
                default="disabled",
                max_length=100,
            ),
        ),
    ]
